In [2]:
import numpy as np

In [4]:
np1 = np.array([1,2,3,4])

In [6]:
np1

array([1, 2, 3, 4])

In [9]:
type(np1)

numpy.ndarray

In [12]:
Mat1 = np.array([[1,2],[3,4]])

In [14]:
Mat1

array([[1, 2],
       [3, 4]])

In [16]:
np1.shape

(4,)

In [17]:
Mat1.shape

(2, 2)

In [19]:
Mat1.dtype 

dtype('int32')

In [21]:
Mat1[0,0] = 5

In [23]:
Mat1

array([[5, 2],
       [3, 4]])

In [26]:
Mat1[0,0] = 'Amay'

ValueError: invalid literal for int() with base 10: 'Amay'

In [28]:
Mat2 = np.arange(0,10,1)

In [30]:
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
Mat3 = np.linspace(0,10,20)

In [35]:
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [37]:
Mat3.shape

(20,)

In [39]:
Mat4 = np.random.rand(5,5)

In [41]:
Mat4

array([[0.61402611, 0.84605289, 0.76650976, 0.74362092, 0.34386134],
       [0.58825221, 0.61679707, 0.05967172, 0.13904532, 0.09121696],
       [0.33117959, 0.51958675, 0.05450229, 0.29728009, 0.69556324],
       [0.93509588, 0.21173427, 0.86209286, 0.47484897, 0.67103529],
       [0.51608062, 0.09613093, 0.50286304, 0.00585295, 0.39822446]])

In [43]:
Mat5 = np.random.rand(5,5)

In [45]:
Mat5

array([[0.63541972, 0.37837083, 0.55750655, 0.75112456, 0.70911595],
       [0.19041272, 0.10909779, 0.47552693, 0.62804949, 0.83827912],
       [0.87751174, 0.830064  , 0.23559097, 0.18089194, 0.07006882],
       [0.13784835, 0.72062332, 0.82404233, 0.09247594, 0.14147201],
       [0.07896588, 0.65637468, 0.47616535, 0.54421761, 0.20019489]])

In [48]:
 Mat5[0,0]

0.6354197230495487

In [50]:
Mat5[0:3,:]

array([[0.63541972, 0.37837083, 0.55750655, 0.75112456, 0.70911595],
       [0.19041272, 0.10909779, 0.47552693, 0.62804949, 0.83827912],
       [0.87751174, 0.830064  , 0.23559097, 0.18089194, 0.07006882]])